#!/bin/bash
set -e
set -o pipefail

echo "============================================================="
echo "      Creating Docker Image                                  "
echo "============================================================="
PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
IMAGE_NAME="registry.heroku.com/${HEROKU_APP_NAME}/web"

#asume that dist folder was created in separate "build artifact" job

mkdir -p ./docker/public
cp -R dist/web-app/. ./docker/public
cp server/server.js docker/
cp stubs/* docker/
rm docker/config.json

echo "============================================================="
echo "          Show directory files                               "
echo "============================================================="
ls -lha docker

cd docker

echo "$HEROKU_KEY" | docker login --username ${HEROKU_OWNER_EMAIL} --password-stdin registry.heroku.com
docker build -t registry.heroku.com/${HEROKU_APP_NAME}/web --build-arg app_version=${PACKAGE_VERSION} .

echo "============================================================="
echo "      Publising Docker Image in Heroku Registry ...          "
echo "============================================================="
docker push registry.heroku.com/${HEROKU_APP_NAME}/web
