#!/usr/bin/env bash
set -e
set -o pipefail

. ci/shared-functions

IS_PROD=$(is_prod_deploy $1)
load_workspace_variables

if [[ $IS_PROD == "yes" && "$BUMP_VERSION_TYPE" == "NOTSEMVER" ]]; then
    skip_deployment
else
    APP_NAME=$(get_app_name $IS_PROD)
    TAG_NAME=$([ $IS_PROD = "yes" ] && echo "release" || echo ${CIRCLE_BRANCH//[\/@\.-]/_})
    imageId=$(docker inspect registry.heroku.com/$APP_NAME/web:$TAG_NAME --format={{.Id}})
    payload='{"updates":[{"type":"web","docker_image":"'"$imageId"'"}]}'

    curl -n -X PATCH https://api.heroku.com/apps/$APP_NAME/formation \
        -d "$payload" \
        -H "Content-Type: application/json" \
        -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
        -H "Authorization: Bearer $HEROKU_KEY"
fi
