#!/usr/bin/env bash
set -e
set -o pipefail

# TODO: this functions should be imported form utils script
get_app_name() {
    [ "$1" = "yes" ] && echo $HEROKU_APP_NAME || echo $HEROKU_APP_NAME_STAGING
}

is_prod_deploy() {
    [ "$1" = "--prod" ] && echo "yes" || echo "no"
}

load_env_variables() {
    echo "============================================================="
    echo "          Check contents of custom-env-variables             "
    echo "============================================================="
    ls -la ./workspace_variables/
    cat ./workspace_variables/custom-env-variables >> $BASH_ENV
    source $BASH_ENV
    cat ./workspace_variables/custom-env-variables
}

skip_deployment() {
    echo "==========================================================================="
    echo "      Merge marked as NOTSEMVER. the production deployment will be skip.   "
    echo "==========================================================================="
    exit 0
}

IS_PROD=$(is_prod_deploy $1)
load_env_variables

if [[ $IS_PROD == "yes" && "$BUMP_VERSION_TYPE" == "NOTSEMVER" ]]; then
    skip_deployment
else
    APP_NAME=$(get_app_name $IS_PROD)
    TAG_NAME=$([ $IS_PROD = "yes" ] && echo "release" || echo ${CIRCLE_BRANCH//[\/@\.-]/_})
    imageId=$(docker inspect registry.heroku.com/$APP_NAME/web:$TAG_NAME --format={{.Id}})
    payload='{"updates":[{"type":"web","docker_image":"'"$imageId"'"}]}'

    curl -n -X PATCH https://api.heroku.com/apps/$APP_NAME/formation \
        -d "$payload" \
        -H "Content-Type: application/json" \
        -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
        -H "Authorization: Bearer $HEROKU_KEY"
fi
