#!/bin/bash

get_app_name() {
    IS_PROD = $1
    [ "$IS_PROD" = "yes" ] && echo $HEROKU_APP_NAME || echo $HEROKU_APP_NAME_STAGING
}

APP_NAME=$(get_app_name $1)
imageId=$(docker inspect registry.heroku.com/$APP_NAME/web --format={{.Id}})
payload='{"updates":[{"type":"web","docker_image":"'"$imageId"'"}]}'

curl -n -X PATCH https://api.heroku.com/apps/$APP_NAME/formation \
-d "$payload" \
-H "Content-Type: application/json" \
-H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
-H "Authorization: Bearer $HEROKU_KEY"