#!/usr/bin/env bash

#Shared functions, import using . ci/shared-functions

load_workspace_variables() {
    echo "============================================================="
    echo "      Check contents of custom-env-variables if exists       "
    echo "============================================================="
    WORKSPACE_VARIABLES_DIR="./workspace_variables/"
    
    if [[ -d $WORKSPACE_VARIABLES_DIR ]]; then
        ls -la ./workspace_variables/
        cat ./workspace_variables/custom-env-variables >> $BASH_ENV
        source $BASH_ENV
        cat ./workspace_variables/custom-env-variables
    else    
        echo "Directory $WORKSPACE_VARIABLES_DIR were not created in latests jobs"
    fi 
}

skip_deployment() {
    echo "==========================================================================="
    echo "      Merge marked as NOTSEMVER. the production deployment will be skip.   "
    echo "==========================================================================="
    exit 0
}

get_app_name() {
    [ "$1" = "yes" ] && echo $HEROKU_APP_NAME || echo $HEROKU_APP_NAME_STAGING
}

is_prod_deploy() {
    [ "$1" = "--prod" ] && echo "yes" || echo "no"
}