#!/usr/bin/env node
const { get } = require('superagent');
const { version } = require('../package.json');

(async function() {
  try {
    // TODO: name should be production or staging app name based in option
    const response = await get('https://boolean-cl-angular-staging.herokuapp.com');
    const htmlContent = response.text;
    const regexForVersionNumber = /<title>.*\s*\|\s*(\d+\.?\d+\.\d+)\s*<\/title>/g;
    const versionFromHtmlDocumentMatch = regexForVersionNumber.exec(htmlContent);

    if (versionFromHtmlDocumentMatch) {
        const actualVersionDeployed = versionFromHtmlDocumentMatch[1];
        if (actualVersionDeployed === version) {
          console.info(`
            SMOKE TEST PASSED:
                ACTUAL VERSION DEPLOYED ${actualVersionDeployed}
                PACKAGE VERSION ON MASTER BRANCH ${version}
          `);
          process.exit(0);
        } else {
          console.error(`
            SMOKE TEST FAILED:
                ACTUAL VERSION DEPLOYED ${actualVersionDeployed}
                PACKAGE VERSION ON MASTER BRANCH ${version}
          `);
          process.exit(1);
        }
    }

  } catch (error) {
      console.error(`
            SMOKE TEST FAILED:
                ERROR WHILE RUNNING: ${error.message}
      `);
      process.exit(1);
  }
})();
