#!/usr/bin/env bash
set -e
set -o pipefail

load_env_variables() {
    echo "============================================================="
    echo "          Check contents of custom-env-variables             "
    echo "============================================================="
    ls -la ./workspace_variables/
    cat ./workspace_variables/custom-env-variables >> $BASH_ENV
    source $BASH_ENV
}

tag_repository() {
    if [[ $BUMP_VERSION_TYPE == "PATCH" ]]; then
        echo "auto semver patch for branch $branch_name_prefix"
        npm version patch
    elif [[ $BUMP_VERSION_TYPE == "MINOR" ]]; then
        echo "auto semver feature for branch $branch_name_prefix"
        npm version minor
    fi

    NEW_PACKAGE_VERSION=$(jq -r ".version" < package.json)
    echo "=============================================================="
    echo "package.json version: $NEW_PACKAGE_VERSION                    "
    echo "package version target: $PACKAGE_VERSION_TARGET               "
    echo "=============================================================="
    echo "                                                           "

    git commit --amend -m "[skip ci] $NEW_PACKAGE_VERSION"
}

load_env_variables

echo "============================================================="
echo "          Updating contributors list                         "
echo "============================================================="
./ci/update-contributors

if [[ "$BUMP_VERSION_TYPE" != "NOTSEMVER" ]]; then
    #try to push if update contributors list were updated
    git push origin ${CIRCLE_BRANCH}
    skip_deployment
else
    tag_repository
    echo "================================================================================"
    echo "     Push repository if exists changes in contributors list and/or tag name     "
    echo "================================================================================"
    git push origin ${CIRCLE_BRANCH}
    git push --follow-tags
fi
